# ── NixOS System Configuration: example-host ─────────────────────────────────
#
# HOW SYSTEM CONFIGURATIONS ARE DISCOVERED:
#   The scaffolding scans `systems/` for subdirectories named after
#   Nix system tuples (e.g., x86_64-linux, aarch64-linux). Within each
#   system directory, every subdirectory becomes a NixOS configuration:
#
#     systems/x86_64-linux/example-host/  ->  nixosConfigurations.example-host
#     systems/aarch64-linux/my-server/    ->  nixosConfigurations.my-server
#
# WHAT THE SCAFFOLDING PROVIDES:
#   For each system configuration, `mkFlake` calls `nixpkgs.lib.nixosSystem`
#   with:
#     - system: inferred from the parent directory name (e.g., "x86_64-linux")
#     - modules: [ universalNixosModule <this-file> ]
#     - specialArgs: allFlakeContext
#
#   The `universalNixosModule` applies the universal overlay so that
#   `pkgs.internal.*` and `pkgs.lib.internal.*` are available.
#
#   `specialArgs` (which becomes extra arguments to all modules) contains:
#     {
#       inputs    - all flake inputs
#       modules   - { nixos = <module tree>; }
#       overlays  - all processed overlays
#       systems   - all NixOS configurations
#       packages  - the raw package tree
#       templates - discovered template directories
#     }
#
# HOW TO EXPORT SYSTEM CONFIGURATIONS:
#   Map them in `exports.nixosConfigurations`:
#
#     exports.nixosConfigurations = { systems, ... }: {
#       example-host = systems.example-host;
#     };
#
# IMPORTING INTERNAL MODULES:
#   Use the `modules.nixos` attr from specialArgs to reference your internal
#   NixOS modules by their tree path.
#
{
  modules,
  inputs,
  # This is the usual nixpkgs instance, with the universal overlay applied.
  pkgs,
  ...
}: {
  # Import internal modules from the module tree.
  imports = with modules.nixos; [
    example
    # If you had modules/nixos/hardware/gpu.nix, you'd reference it as:
    # hardware.gpu
  ];

  # ── Basic system configuration ──

  # Required: set the state version to match your initial NixOS install.
  system.stateVersion = "25.11";

  # Boot loader configuration (adjust to match your hardware).
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Networking.
  networking.hostName = "example-host";

  # Enable the scaffold example service from our internal module.
  services.scaffold-example = {
    enable = true;
    greeting = "Hello from example-host!";
  };

  # ── Accessing internal packages ──
  # Because the universal overlay is applied, all internal packages
  # are available under pkgs.internal.*
  environment.systemPackages = [
    # pkgs.internal.greeter   -- already installed by the module above
    # pkgs.internal.hello     -- another internal package
  ];

  # ── Filesystem (required for a bootable system) ──
  # In a real configuration, you would include hardware-configuration.nix
  # generated by `nixos-generate-config`.
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };
}
